name: 'Lint'

on:
  workflow_call: 
  workflow_dispatch:

jobs:
  pytorch_pylint:
    name: 'pytorch_lint'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout (attempt 1)
        id: checkout1
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          fetch-depth: 0

      - name: Checkout (attempt 2)
        id: checkout2
        if: steps.checkout1.outcome == 'failure'
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          fetch-depth: 0

      - name: Checkout (attempt 3)
        if: steps.checkout2.outcome == 'failure'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Python
        run: |
          sudo apt-get update -q
          sudo apt-get install -y -q python3-pip
          pip3 install torch numpy --quiet

      - name: Run Lint
        env:
          TE_PATH: ${{ github.workspace }}
          PYTHON_ONLY: '1'
        run: bash ./qa/L0_pytorch_lint/test.sh
        timeout-minutes: 15
